import { describe, expect, it } from "vitest";
import { eventContext, narrativeKey, matchMetrics } from "./narrativeContext";
import type { MatchEvent } from "./types";
const event = (type: string, minute: number, side: "Home" | "Away" = "Home", player = "p1"): MatchEvent => ({ event_type: type, minute, side, player_id: player, secondary_player_id: null, zone: "Midfield" });
describe("truthful match narratives", () => {
  it("does not read goals from the future", () => { const e = event("Goal", 10); expect(eventContext(e, [e, event("Goal", 50)]).ownAfter).toBe(1); });
  it("distinguishes goals in the same minute", () => { const a = event("Goal", 10); const b = event("Goal", 10, "Home", "p2"); expect(eventContext(a, [a,b]).ownAfter).toBe(1); });
  it("accepts snapshot copies of an event", () => { const e = event("Goal", 10); expect(eventContext({...e}, [e, event("Goal", 20)]).ownAfter).toBe(1); });
  it("includes the current event when absent from snapshot", () => { const e = event("Goal", 10); expect(eventContext(e, []).ownAfter).toBe(1); });
  it("counts in-match penalties as goals", () => { const a = event("PenaltyGoal", 10); const b = event("Goal", 20); expect(eventContext(b,[a,b]).ownAfter).toBe(2); });
  it("excludes shootout kicks from the match score", () => { const a = event("ShootoutGoal", 10); const b = event("Goal",20); expect(eventContext(b,[a,b]).ownAfter).toBe(1); });
  it("recognizes late equalisers", () => { const a=event("Goal",10,"Away"); const b=event("Goal",88); expect(narrativeKey(b,[a,b])).toBe("lateEqualiser"); });
  it("does not call an early equaliser late", () => { const a=event("Goal",10,"Away"); const b=event("Goal",30); expect(narrativeKey(b,[a,b])).not.toBe("lateEqualiser"); });
  it("recognizes a comeback lead", () => { const a=event("Goal",10,"Away"); const b=event("Goal",30); const c=event("Goal",60,"Home","p2"); expect(narrativeKey(c,[a,b,c])).toBe("comebackLead"); });
  it("does not invent a comeback from a level match", () => { const e=event("Goal",60); expect(narrativeKey(e,[e])).not.toBe("comebackLead"); });
  it("describes a late lead without promising victory", () => { const e=event("Goal",89); expect(narrativeKey(e,[e])).toBe("lateLead"); });
  it("identifies a fourth goal milestone", () => { const events=[10,20,30,40].map(m=>event("Goal",m)); expect(narrativeKey(events[3],events)).toBe("fourGoals"); });
  it("tracks milestones separately by scorer", () => { const a=event("Goal",10); const b=event("Goal",20,"Home","p2"); expect(eventContext(b,[a,b]).playerGoals).toBe(1); });
  it("records score from the away perspective", () => { const a=event("Goal",10,"Home"); const b=event("Goal",20,"Away"); expect(eventContext(b,[a,b]).opponentBefore).toBe(1); });
  it("counts rolling pressure only in its window", () => { const a=event("ShotSaved",3); const b=event("Corner",20); expect(eventContext(b,[a,b]).recentShots).toBe(0); });
  it("pressure never leaks between teams", () => { const a=event("ShotSaved",19,"Away"); const b=event("Corner",20); expect(eventContext(b,[a,b]).recentShots).toBe(0); });
  it("recognizes late pressure from actual shots", () => { const events=[event("ShotSaved",80),event("ShotBlocked",81),event("Corner",82)]; expect(narrativeKey(events[2],events)).toBe("sustainedPressure"); });
  it("identifies a first yellow without a prior booking", () => { const e=event("YellowCard",20); expect(narrativeKey(e,[e])).toBe("bookingRisk"); });
});
