//! Generated-squad planning for database-free careers.
use crate::generated_balance::{academy_potential,club_role_target_ovr,weekly_wage_eur,LeagueTier,SquadRole};
pub const GENERATED_SQUAD_SIZE:usize=22;
#[derive(Debug,Clone,Copy,PartialEq,Eq)]pub enum SquadGroup{Goalkeeper,Defender,Midfielder,Forward}
pub fn group_for_slot(slot:usize)->SquadGroup{match slot{0..=1=>SquadGroup::Goalkeeper,2..=8=>SquadGroup::Defender,9..=15=>SquadGroup::Midfielder,_=>SquadGroup::Forward}}
pub fn minimum_group_count(group:SquadGroup)->usize{match group{SquadGroup::Goalkeeper=>2,SquadGroup::Defender=>4,SquadGroup::Midfielder=>4,SquadGroup::Forward=>2}}
pub fn role_for_slot(slot:usize)->SquadRole{match slot{0|2|3|9|10|16=>SquadRole::Starter,4|5|11|12|17=>SquadRole::Rotation,6|13|18|19=>SquadRole::Depth,7|14|20=>SquadRole::Prospect,1|8|15|21=>SquadRole::Academy,_=>SquadRole::Depth}}
pub fn senior_age_range(role:SquadRole)->(u8,u8){match role{SquadRole::Star=>(22,31),SquadRole::Starter=>(21,32),SquadRole::Rotation=>(20,33),SquadRole::Depth=>(20,34),SquadRole::Prospect=>(17,22),SquadRole::Academy=>(16,20)}}
pub fn target_age_for_slot(slot:usize)->u8{let(lo,hi)=senior_age_range(role_for_slot(slot));lo+((slot as u8*3)%(hi-lo+1))}
pub fn captain_candidate(slot:usize)->bool{matches!(slot,0|2|3|9|10)&&target_age_for_slot(slot)>=24}
pub fn elite_star_slots(tier:LeagueTier,reputation:u8,financial_strength:u8)->usize{if !matches!(tier,LeagueTier::Elite|LeagueTier::Top){return 0}let strength=(reputation.min(100)as u16+financial_strength.min(100)as u16)/2;match strength{90..=100=>4,80..=89=>3,70..=79=>2,60..=69=>1,_=>0}}
pub fn slot_variance(slot:usize)->i8{match slot%7{0=>2,1=>-2,2=>1,3=>0,4=>-1,5=>1,_=>-1}}
pub fn target_ovr_for_slot(slot:usize,tier:LeagueTier,reputation:u8,financial_strength:u8)->u8{let mut role=role_for_slot(slot);let stars=elite_star_slots(tier,reputation,financial_strength);if stars>0&&matches!(slot,0|2|9|10|16){let rank=match slot{16=>0,10=>1,9=>2,2=>3,_=>4};if rank<stars{role=SquadRole::Star}}let base=club_role_target_ovr(tier,role,reputation,financial_strength)as i16;(base+slot_variance(slot)as i16).clamp(30,94)as u8}
pub fn target_potential_for_slot(slot:usize,tier:LeagueTier,reputation:u8,academy_quality:u8)->u8{let current=target_ovr_for_slot(slot,tier,reputation,academy_quality);match role_for_slot(slot){SquadRole::Academy|SquadRole::Prospect=>academy_potential(tier,reputation,academy_quality,current),_=>current.saturating_add(2).min(94)}}
pub fn estimated_weekly_payroll(tier:LeagueTier,reputation:u8,financial_strength:u8)->i64{(0..GENERATED_SQUAD_SIZE).map(|slot|weekly_wage_eur(target_ovr_for_slot(slot,tier,reputation,financial_strength),reputation)).sum()}
pub fn payroll_guardrail(tier:LeagueTier,reputation:u8,financial_strength:u8,weekly_budget:i64)->bool{estimated_weekly_payroll(tier,reputation,financial_strength)<=weekly_budget}
#[cfg(test)]mod tests{use super::*;#[test]fn academy_slots_stay_young(){for slot in[1,8,15,21]{assert_eq!(role_for_slot(slot),SquadRole::Academy);assert!(target_age_for_slot(slot)<=20)}}#[test]fn squad_has_captain_candidate(){assert!((0..GENERATED_SQUAD_SIZE).any(captain_candidate))}#[test]fn poor_lower_clubs_have_no_forced_stars(){assert_eq!(elite_star_slots(LeagueTier::Lower,95,95),0)}#[test]fn generated_shape_has_two_goalkeepers(){assert_eq!((0..GENERATED_SQUAD_SIZE).filter(|s|group_for_slot(*s)==SquadGroup::Goalkeeper).count(),2)}#[test]fn rich_elite_starter_beats_lower_tier_equivalent(){assert!(target_ovr_for_slot(16,LeagueTier::Elite,95,95)>target_ovr_for_slot(16,LeagueTier::Lower,45,40))}#[test]fn academy_potential_exceeds_current(){let o=target_ovr_for_slot(21,LeagueTier::Elite,90,90);assert!(target_potential_for_slot(21,LeagueTier::Elite,90,90)>o)}#[test]fn elite_payroll_exceeds_lower_payroll(){assert!(estimated_weekly_payroll(LeagueTier::Elite,90,90)>estimated_weekly_payroll(LeagueTier::Lower,45,45))}#[test]fn slots_have_quality_variation(){assert_ne!(slot_variance(0),slot_variance(1))}}
