import { useTranslation } from "react-i18next";
import type { GameStateData } from "../store/gameStore";
import { Badge, TeamLogo } from "./ui";
import { getTeamName,getUserCompetition,getUserNextFixture,formatMatchDate,isSeasonComplete } from "../lib/helpers";

export default function NextMatchDisplay({gameState}:{gameState:GameStateData}){
 const {t}=useTranslation(); const userTeamId=gameState.manager.team_id; const league=getUserCompetition(gameState);
 if(!userTeamId||!league)return <p className="py-4 text-center text-sm text-gray-500 dark:text-gray-400">{t("home.noLeagueSchedule")}</p>;
 const nextFixture=getUserNextFixture(gameState); if(!nextFixture)return <p className="py-4 text-center text-sm text-gray-500 dark:text-gray-400">{t(isSeasonComplete(league)?"home.seasonComplete":"home.noUpcomingOpponent")}</p>;
 const isHome=nextFixture.home_team_id===userTeamId; const opponentId=isHome?nextFixture.away_team_id:nextFixture.home_team_id; const userTeam=gameState.teams.find(x=>x.id===userTeamId); const opponentTeam=gameState.teams.find(x=>x.id===opponentId);
 const fixtureLabel=nextFixture.competition==="League"?t("home.matchdayN",{n:nextFixture.matchday}):nextFixture.competition==="PreseasonTournament"?t("season.preseasonTournament"):t("season.friendly");
 const renderTeam=(team:typeof userTeam,id:string,primary=false)=><div className="min-w-0 flex-1 text-center">{team&&<TeamLogo team={team} className={`mx-auto mb-1.5 flex h-11 w-11 items-center justify-center overflow-hidden rounded-full border-2 sm:mb-2 sm:h-16 sm:w-16 ${primary?"border-primary-200 dark:border-primary-800":"border-gray-300 dark:border-navy-600"}`} imageClassName="h-8 w-8 object-contain drop-shadow sm:h-12 sm:w-12" style={{backgroundColor:team.colors.primary}}/>}<p className={`mx-auto line-clamp-2 max-w-28 break-words font-heading text-[11px] font-bold uppercase leading-tight tracking-wide sm:max-w-none sm:text-sm ${primary?"text-primary-600 dark:text-primary-400":"text-gray-500 dark:text-gray-400"}`}>{getTeamName(gameState.teams,id)}</p></div>;
 return <div className="overflow-hidden rounded-xl border border-gray-100 bg-gray-50 px-2 py-3 transition-colors dark:border-navy-600 dark:bg-navy-800 sm:px-4 sm:py-6"><div className="grid min-w-0 grid-cols-[minmax(0,1fr)_4.75rem_minmax(0,1fr)] items-center gap-1.5 sm:grid-cols-[1fr_auto_1fr] sm:gap-4">{renderTeam(userTeam,userTeamId,true)}<div className="flex min-w-0 flex-col items-center gap-1 text-center"><span className="font-heading text-lg font-bold leading-none text-gray-300 dark:text-navy-600 sm:text-2xl">VS</span><Badge variant="neutral" size="sm">{formatMatchDate(nextFixture.date)}</Badge><span className="line-clamp-2 max-w-[4.75rem] text-[9px] leading-tight text-gray-400 dark:text-gray-500 sm:max-w-24 sm:text-xs">{fixtureLabel}</span><Badge variant={isHome?"success":"accent"} size="sm">{isHome?t("home.home"):t("home.away")}</Badge></div>{renderTeam(opponentTeam,opponentId)}</div></div>;
}